# Generated by Django 3.0.2 on 2020-01-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=100)),
                ('bookYear', models.DateField(blank=True, null=True)),
                ('bookDetail', models.TextField(max_length=500)),
                ('borrowedBy', models.CharField(blank=True, max_length=100)),
                ('borrowedDate', models.DateField(blank=True, null=True)),
                ('isBorrowed', models.BooleanField(default=False)),
                ('isReturned', models.DateField(blank=True, null=True)),
                ('returnedDate', models.DateField(blank=True, null=True)),
                ('bookWriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knihovna.Author')),
            ],
        ),
    ]
