# Generated by Django 3.0.2 on 2020-01-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0002_auto_20200130_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='returnedDate',
        ),
        migrations.AddField(
            model_name='book',
            name='returnDate',
            field=models.DateField(blank=True, null=True, verbose_name='Return date'),
        ),
    ]
