# Generated by Django 3.0.2 on 2020-02-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0005_auto_20200131_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isBorrowed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
